name: Lisboa Live
favicon: null
layout_spectrum: 0.74855
typography_spectrum: 0.61175
title: 'A marca LISBOA LIVE , é uma plataforma única de Social Media altamente interativa inserida nas maiores redes sociais do mundo - Facebook e Instagram.   É um projeto inovador na área da Promoção Turistica e do Marketing Digital que tem como principal objectivo promover o melhor que Portugal tem para oferecer LIVE'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
